let shopitemsdata = [{
    id:"a",
    name: "Earl Grey chocolate ice cream",
    price: "50",
    desc: "This Earl Grey chocolate ice cream has a deep, rich chocolate taste layered with a beautiful Earl",
    img: "images/a.jpg",
},
{
    id:"b",
    name: "Chocolate Cake",
    price: "200",
    desc: "Simply the best chocolate cake I've ever had. Rich, ultra moist, fluffy and that chocolate",
    img: "images/b.jpg",
},
{
    id:"c",
    name: "Pink Drip Cake",
    price: "170",
    desc: "Whether you're celebrating a baby shower, birthday, or just love the color pink, this vanilla pink",
    img: "images/c.jpg",
},
{
    id:"d",
    name: "Naked Birthday Cake",
    price: "240",
    desc: "A Naked Birthday Cake with layers of cake, lemon curd, crushed meringues, swiss buttercream",
    img: "images/d.jpg",
},
{
    id:"e",
    name: "Vegan Chocolate Truffle Cake",
    price: "350",
    desc: "On a scale of deliciousness from 1 to 10, this vegan chocolate truffle cake is off the charts",
    img: "images/e.webp",
},
{
    id:"f",
    name: "Cassata Cake",
    price: "190",
    desc: "In Sicily, the long-ago homeland of immigrants who first brought cassata cake to America",
    img: "images/f.webp",
},
{
    id:"g",
    name: "Oreo Whipped Cream Cake",
    price: "260",
    desc: "This simple yet impressive chocolate cake is layered and topped with Oreo whipped cream",
    img: "images/g.jpg",
},
{
    id:"h",
    name: "Funfetti Cake",
    price: "500",
    desc: "A moist and delightful funfetti cake filled with cheerful sprinkles, coated in creamy Italian",
    img: "images/h.webp",
},
{
    id:"i",
    name: "Nutella Cake",
    price: "365",
    desc: "Nutella, chocolate and ice-cream in one delicious dessert. Dreams really do come true.",
    img: "images/i.jpeg",
},
{
    id:"j",
    name: "Strawberry Vanilla Cake",
    price: "630",
    desc: "This is wedding cake made up of Strawberry and Vanilla ",
    img: "images/j.jpeg",
},
{
    id:"k",
    name: "Chocolate Lamington Cake",
    price: "520",
    desc: "I love lamingtons, I still buy the packs of 24! I wanted to create an impressive dessert",
    img: "images/k.jpg",
},
{
    id:"l",
    name: "Filipino Purple Cake",
    price: "160",
    desc: "Ube cake (or Filipino purple cake) is unlike any cake you’ve had before. It’s sweet and earth",
    img: "images/l.jpg",
},
{
    id:"m",
    name: "Blue Drip Cream Cake",
    price: "620",
    desc: "This extra tall ice cream cake is airbrushed royal blue and decorated with rock candy, merengues, chocolate pieces and chocolate ganache drip.",
    img: "images/m.jpg",
},
{
    id:"n",
    name: "Funfetti Vanilla Cake",
    price: "430",
    desc: "This is the PERFECT funfetti cake recipe! It's super moist, soft, and loaded with sprinkles.",
    img: "images/n.jpg",
},
{
    id:"o",
    name: "Vegan Chocolate Truffle Cake",
    price: "210",
    desc: "UOn a scale of deliciousness from 1 to 10, this vegan chocolate truffle cake is off the charts",
    img: "images/o.jpg",
},
{
    id:"p",
    name: "Velvet Cake",
    price: "480",
    desc: "The classic, iconic Velvet Cake! The sponge is soft and velvety",
    img: "images/p.png",
},
{
    id:"q",
    name: "Blue Velvet Cake",
    price: "730",
    desc: "This Blue Velvet Cake is almost as pretty as it is tasty! Customize by using your favorite frosting",
    img: "images/q.webp",
},
{
    id:"r",
    name: "Filipino Chiffon Cake",
    price: "690",
    desc: "Ube Cake is a traditional Filipino chiffon cake or sponge cake made with ube halaya. It is distinctively vividly purple in color, like most dishes made with",
    img: "images/r.jpg",
},
{
    id:"s",
    name: "White Cake",
    price: "80",
    desc: "Classic White Cake with Vanilla Bean Buttercream",
    img: "images/s.webp",
},
{
    id:"t",
    name: "Pink Rose Cake",
    price: "570",
    desc: "An intricate s-scroll border intertwines this delicate pink cake with majestic buttercream Wilton Roses adorning the top.",
    img: "images/t.jpg",
},
];
